import type { Metadata } from "next";
import { StyledWrapper } from "@/style/styled-wrapper";
import "@/style/global.css";
import Providers from "@/utils/provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <StyledWrapper>
          <Providers>{children}</Providers>
        </StyledWrapper>
      </body>
    </html>
  );
}
