import type { Metadata } from "next";
import "./global.css";
import Providers from "@/utils/provider";
import { MainLayout } from "@/components/layout/MainLayout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <MainLayout>
            {children}
            {modal}
          </MainLayout>
        </Providers>
      </body>
    </html>
  );
}
