name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH and deploy with Docker
        env: 
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem -T $EC2_USER@$EC2_HOST << 'EOF'
            cd /home/ubuntu/SNS_Project
            git pull origin main
            docker-compose pull app # app 서비스의 이미지를 최신으로 가져옴
            docker-compose up -d --build # 변경된 내용을 적용하며 컨테이너를 빌드 및 재시작
            docker image prune -f # 불필요한 이미지를 삭제해 디스크 공간 확보
          EOF
          rm private_key.pem
        shell: bash
